fixture_blog/config/routes.rb
WorkreportBlog::Application.routes.draw do
  match '/admin' => 'admin#index'
  namespace :admin do
    resources 'posts', :controller => 'blog_posts', :as => 'blog_post', :except => [:show]
  end

  resources 'posts', :controller => 'blog_posts', :as => 'blog_post', :only => [:index,:show] do
    resources 'comments', :only => [:new]
  end

  resources 'comments', :only => [:create, :new] do
    member do
      get :reply, :to => :new
    end
  end
  root :to => redirect('/posts')
end

fixture_blog/app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :as => :parent
  has_many :all_comments, :class_name => 'Comment'

  validates :user,    :presence   => true
  validates :title,   :length     => 5..25
  validates :content, :presence   => true

  scope :published, where('publish_at <= ?', Time.zone.now.to_s(:db))
end

fixture_blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :parent, :polymorphic => true
  belongs_to :blog_post
  has_many :replies, :class_name => 'Comment', :as => :parent
  validates :name,  :length   => 4..25,
                    :format   => /\A[A-Za-z0-9\-_ ]*\Z/
  validates :parent, :presence => true
  validates :content, :length => 1..400
  validates :blog_post, :presence => true

  validate :validates_parent

  before_validation :set_blog_post_id
private
  def validates_parent
    return if parent.nil? || (parent.class.name == self.class.name)
    unless parent.publish_at && parent.publish_at <= Time.zone.now
      errors.add(:parent,"Post must be published to comment") 
    end

    if self.parent == self
      errors.add(:parent,"Parent cannot be self")
    end
  end

  def set_blog_post_id
    return if self.parent.nil?

    if self.parent.is_a? BlogPost
      self.blog_post = self.parent
    elsif self.parent.is_a? Comment
      self.blog_post = self.parent.blog_post
    end
  end
end

fixture_blog/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password_raw

  has_many :blog_posts

  validates :username,  :uniqueness => true,
                        :length     => 5..25,
                        :format     => /\A[a-zA-Z0-9_]+\Z/

  validates :password,  :length     => 40..40,
                        :format     => /\A[a-z0-9]+\Z/
  
  before_validation :generate_hash, :on => :create

  def self.password_hash(username,password)
    Digest::SHA1.hexdigest "#{username}:#{password}"
  end

  def self.authenticate(username,password)
    User.where(
      :username => username,
      :password => User.password_hash(username,password)
    ).first
  end

  def generate_hash
    self.password = User.password_hash(
      self.username,
      self.password_raw
    )
  end
end

fixture_blog/app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :authenticate
private
  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      @session_user = User.authenticate(username,password)
    end
  end
end

fixture_blog/app/controllers/admin/blog_posts_controller.rb
class Admin::BlogPostsController < Admin::BaseController
  before_filter :build_blog_post, :only => [:new, :create]
  before_filter :load_blog_post, :only => [:edit, :update, :destroy]

  def index
    @blog_posts = BlogPost.all
  end

  def new
  end
  
  def create
    @blog_post.save!
    flash[:notice] = 'Blog Post Created'
    redirect_to :action => :index
  rescue ActiveRecord::RecordInvalid
    render :action => :new
  end

  def edit
  end

  def update
    @blog_post.update_attributes!(params[:blog_post])
    redirect_to :action => :edit
  rescue ActiveRecord::RecordInvalid
    render :action => :edit
  end

  def destroy
    @blog_post.destroy
    flash[:notice] = 'Blog Post Deleted'
    redirect_to :action => :index
  end

private
  def build_blog_post
    @blog_post = BlogPost.new(params[:blog_post])
    @blog_post.user = @session_user
  end

  def load_blog_post
    @blog_post = BlogPost.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render :text => 'No Post with that Id', :status => :not_found
  end
end

fixture_blog/app/controllers/admin_controller.rb
class AdminController < Admin::BaseController
  def index
  end
end

fixture_blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

fixture_blog/app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  def index
    @blog_posts = BlogPost.published
  end

  def show
    @blog_post = BlogPost.published.find(params[:id])
    @comments = BlogPost.published
  rescue ActiveRecord::RecordNotFound
    render :text => 'No Post with that Id', :status => :not_found
  end
end

fixture_blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new(params[:comment])

    if params[:id].present?
      @comment.parent = Comment.find(params[:id])
      @comment.blog_post = @comment.parent.blog_post
    else
      blog_post = BlogPost.find(params[:blog_post_id])
      @comment.blog_post = blog_post
      @comment.parent = blog_post
    end
  end

  def create
    @comment = Comment.new(params[:comment])
    @comment.save!  
    redirect_to blog_post_path(@comment.blog_post)
  rescue ActiveRecord::RecordInvalid
    render :action => :new
  end
end

fixture_blog/app/helpers/admin/blog_posts_helper.rb
module Admin::BlogPostsHelper
end

fixture_blog/app/helpers/admin_helper.rb
module AdminHelper
end

fixture_blog/app/helpers/application_helper.rb
module ApplicationHelper
end

fixture_blog/app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

fixture_blog/app/helpers/comments_helper.rb
module CommentsHelper
end

fixture_blog/app/views/admin/blog_posts/_form.html.haml
- action = @blog_post.new_record? ? :create : :update

= form_for @blog_post, :url => {:action => action} do |f|
  - @blog_post.errors.full_messages.each do |msg|
    .err{:style => 'color:red'}
      = msg
  .field
    Title
    = f.text_field :title
  .field
    Publish At
    = f.datetime_select :publish_at
  .field
    Content
    = f.text_area :content
  .field
    = f.submit 'Save'

fixture_blog/app/views/admin/blog_posts/edit.html.haml
%h1 Editing Blog Post
= render :partial => 'form'

fixture_blog/app/views/admin/blog_posts/index.html.haml
- @blog_posts.each do |blog_post|
  %h1= blog_post.title
  = link_to 'Edit', edit_admin_blog_post_path(blog_post)
  OR
  = link_to 'Delete', admin_blog_post_path(blog_post), :method => :delete, :confirm => 'Are you sure?'
  %hr/

= link_to 'Add New', new_admin_blog_post_path

fixture_blog/app/views/admin/blog_posts/new.html.haml
%h1 New Blog Post
= render :partial => 'form'

fixture_blog/app/views/admin/index.html.haml
= link_to 'Blog Posts', admin_blog_post_index_path

fixture_blog/app/views/blog_posts/_comment.html.haml
%li
  %h2= comment.name
  %p= comment.content
  = link_to 'Reply', reply_comment_path(comment)
  - if comment.replies.present?
    %ul
      = render :partial => 'comment', :collection => comment.replies

fixture_blog/app/views/blog_posts/index.html.haml
- @blog_posts.each do |post|
  %h1= link_to post.title, blog_post_path(post)
  %p= post.content
  %hr/

fixture_blog/app/views/blog_posts/show.html.haml
%h1= @blog_post.title
%p= @blog_post.content
%hr/
- if @blog_post.comments.present?
  %ul
    = render :partial => 'comment', :collection => @blog_post.comments

= link_to 'Comment on this Post', new_blog_post_comment_path(@blog_post)

= link_to 'Back to Index', blog_post_index_path

fixture_blog/app/views/comments/new.html.haml
= form_for @comment do |f|
  - @comment.errors.full_messages.each do |msg|
    .err{:style => 'color:red'}
      = msg
  = f.hidden_field :blog_post_id
  = f.hidden_field :parent_id
  = f.hidden_field :parent_type
  .field
    Name:  
    = f.text_field :name
  .field
    Content:
    = f.text_area :content
  .field
    = f.submit 'Save'

- if @comment.blog_post.present?
  = link_to 'Back to Post', blog_post_path(@comment.blog_post)

fixture_blog/app/views/layouts/application.html.haml
!!! XML
!!! 1.0
%html
  %head
    %title Blog
  %body
    = yield